services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 5s

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_fiber
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    command: ["./main"]

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
