services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    restart: always

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    volumes:
    - .:/app
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
